<?xml version="1.0" encoding="utf-8"?><Database Name="TERRABIT 2015 DEV" EntityNamespace="NavScm.NavInterface" ContextNamespace="NavScm.NavInterface" Class="NavSQLDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Object" Member="NavDBObject">
    <Type Name="NavDBObject">
      <Column Name="timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" IsReadOnly="true" CanBeNull="false" IsVersion="true" />
      <Column Name="Type" Modifier="Override" Type="System.Int32" DbType="Int NOT NULL" IsReadOnly="true" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Company Name]" Member="CompanyName" Storage="_Company_Name" Type="System.String" DbType="VarChar(30) NOT NULL" IsReadOnly="true" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Modifier="Override" Type="System.Int32" DbType="Int NOT NULL" IsReadOnly="true" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Modifier="Override" Type="System.String" DbType="VarChar(30) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Modified" Member="IsModified" Storage="_Modified" Type="System.Byte" DbType="TinyInt NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Compiled" Member="IsCompiled" Storage="_Compiled" Type="System.Byte" DbType="TinyInt NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Date" Member="ModifiedDate" Storage="_Date" Modifier="Override" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Time" Member="ModifiedTime" Storage="_Time" Modifier="Override" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="[Version List]" Member="VersionList" Storage="_Version_List" Modifier="Override" Type="System.String" DbType="VarChar(248) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Locked" Type="System.Byte" DbType="TinyInt NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="[Locked By]" Member="LockedBy" Storage="_Locked_By" Type="System.String" DbType="VarChar(132) NOT NULL" IsReadOnly="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>